### ISSUE TITLE
MEDIA_ROOT makes test fail

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#1]
Right now, MEDIA_ROOT is defined as:
```
MEDIA_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(BASE_DIR))) + '/users'
```
https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/master/chris_backend/config/settings/local.py#l30

If the `MEDIA_ROOT` directory doesn't exist on the file system, it makes the feed test_views fail because it tries to create `test` user in a directory that doesn't exist (/users).

2 possibilities:
-require the '/users' directory to be there (add a test for it to make sure there is a '/users' directory) - will also update vagrant/bootstrap.sh to create the /users directory.

or

-use `makedirs ` instead of `mkdir` to recursively create the directories that do not exist.

thoughts @jbernal0019?

**Comment by jbernal0019** [comment]
I've just fixed it by modifying the local.py settings to create the MEDIA_ROOT if it doesn't exist

**Comment by NicolasRannou** [comment]
👍
