### ISSUE TITLE
inter-node I/O filtering

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ultron_backEnd#102]
Track efforts related to filtering I/O between nodes

**Comment by rudolphpienaar** [comment]
Possible use a ``--inputPathFilter`` spec in plugin representation that is interpreted by ``pfcon``.

**Comment by jbernal0019** [comment]
Wasn't this achieved by using the new topological plugins (`ts` plugins) with the `--filter <filter>` parameter?

**Comment by rudolphpienaar** [comment]
Yes --- you can close this. Looks like it is from three years ago.
