### ISSUE TITLE
Allow authentication token to be passed as part of the url (like a query param) when clients make a GET request to download a file.

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_ultron_backEnd#111]

**Comment by jbernal0019** [comment]
1. This complicates BE implementation

2. It is non standard and insecure (as commented here https://github.com/encode/django-rest-framework/issues/1113)

3. Pose a problem for FE when tokens expire (how to handle an <img> tag request failure when the auth token has just expired). 

4. In addition we don't want the client apps to rely on URLs as they can change with new API versions. We want the client ChRIS app to use the already developed JS client for the ChRIS REST API which harnesses the hypermedia-based API design and abstracts urls into object methods.

**Comment by arielkaluzhny** [comment]
Hello, I'm having this issue. Is there a way to set the Authorization token in the header when making a GET request to download?

**Comment by shawnngtq** [comment]
@jbernal0019 

Hi, despite all the points mention.

As of today, if I wish to make my API accepts token passed via URL, what will be the cleanliest / DRY method to do it?

Should I update the `TokenAuthentication`'s `authenticate` method?
