### ISSUE TITLE
Allow GET + parameters queries

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#12]
It will be important to let user query the API using parameters.
Is it supported already? If so, where can I see the list of supported parameters?

Use case:

```
GET Feed + favorite=true
GET Feeds + tag="grantX" + tag="topSecret"
Get Tags + username="nicolas"
```

**Comment by NicolasRannou** [comment]
cc @jbernal0019

**Comment by jbernal0019** [comment]
The urls for query searches are going to be part of the `queries`  list of the query templates in the returned Collection+Json document for a collection. The urls are of the form `list_url/search?prop1=val1&prop2=val2...`

Currently we are implementing an additional readonly view for each collection for which we want to implement query searches. Eg. the Plugin collection has an additional view called `PluginListQuerySearch` that returns the appropriate response.
