### ISSUE TITLE
Manage production secrets. 

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_ultron_backEnd#144]
Basically add a secrets_template.json file. Add chris_secrets.json  and chris_store_secrets.json names to .gitignore.

To start Chris or Chris store production images we first make a copy of secrets_template.json file with the proper name (chris_secrets.json or chris_store_secrets.json) and then appropriately  change existing secrets or add new secrets there. 

The production images will mount the secrets file on the appropriate directory for the Django app.

**Comment by rudolphpienaar** [comment]
This seems to be affecting `docker-compose logs`...?

**Comment by jbernal0019** [comment]
Secrets are finally managed through .env files containing secret variables as well as configuration variables as environment variables.
