### ISSUE TITLE
Target Power9 computing architectures

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ultron_backEnd#221]
As an ancillary to AIM 2, ChRIS backend resources are currently being deployed to schedule  ppc64le architected containers. The MOC currently has several IBM Power9 compute nodes provisioned with GPUs that would be ideal candidates for COVID-NET compute scheduled via ChRIS.

@rpienaar is putting in a proposal to mentor a graduate-level cloud computing CS course in the Fall 2020 semester @ BU & Northeastern. AIM 1 could be a graduate semester project, so odds are there might be a student team coming onboard in Sept specifically focused on running the inference on Power9 and helping around that. 

The task here would be to help Rudolph mentor these students when they come on board.

Resource:
https://github.com/FNNDSC/ubuntu-python3#manifest-list (Jennings Zhang's research on ChRIS + POWER9)

**Comment by junaruga** [comment]
Oh sorry I removed my assignment by my mistake. Could you assign myself again?

**Comment by junaruga** [comment]
I would like to remindr you.

> @RPienaar is putting in a proposal to mentor a graduate-level cloud computing CS course in the Fall 2020 semester @ BU & Northeastern. 

@RPienaar when can we start this task?
@jennydaman I remember you had motivation to implement this updating Travis CI.

I assumed the following assignments, though I was assigned on this GitHub ticket.

1. Jennings will implement the imported common yaml file
2. People in cloud computing CS course will work for each `pl-` repository.

**Comment by junaruga** [comment]
Okay. How can we find "the RH employee who has access to the MOC and experience in setting up openshit projects in the MOC"? @mairin, Did you work with this kind of Red Hat employee in the past in ChRIS?

**Comment by jennydaman** [comment]
Mostly done
