### ISSUE TITLE
Add timing logic to pipelines in ChRIS backend

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_ultron_backEnd#234]
This task involves adding functionality in the innards of ChRIS (mainly pfcon)

**The use case:** 
An end user has their own plugin image that ChRIS is supposed to inject into an existing pipeline. There is a ChRIS pipeline that should make a new feed with test data, run their plugin, and then evaluate the results. 

Right now it isn't possible to create a ChRIS feed by calling the API without waiting for ancestor nodes to finish. This limits the amount of automation we can achieve. If you try to create a ChRIS feed a launch all nodes right away - any node with incomplete ancestors will look in swift, see that the output isn't there yet, and fail. 

**Proposed solution:**
Add timing / waiting logic to ChRIS pipelines, such that a script using the API can run unattended and successfully create a feed based on a pipeline without intervention required. Practically what this would mean is that any descendant nodes waiting on an ancestor to finish, instead of failing the first time the direct ancestor's output is not available, they would have the ability to poll until the output is available, and then carry on.

Note that this is how the COVID-Net javascript client works; the timing logic would be good to have on the server instead of the client side though so each client doesn't have to write its own timing logic.

**Long-term:**
Enabling polling for nodes isn't meant to be a long-term solution, so we're not looking for big architectural changes or complicated fixes here. We're just looking to implement polling so we can get ChRIS out the door with the ability to deploy pipelines/trees full of nodes without requiring human intervention. Later on down the line, we will revisit this and come up with a less hacky solution. 

**Potential conditions to think about handling:**

1) **Real failure up the tree** - if a plugin node up the tree fails for real reasons (not just that its direct ancestor didn't finish yet) , the nodes further down the tree (or maybe all other pending / processing nodes) should be shut down maybe instead of sitting there polling, waiting for a completed ancestor that will never appear?

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/commit/53155059db5990292089badb420facdc57b7d9a4
