### ISSUE TITLE
List index out of range after restarting PMAN

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#28]
NOTE FROM RUDOLPH: These steps are not necessarily guaranteed to recreate the issue always. The key is killing pman before it saves its internal database. This is not always guaranteed. If pman has saved its internal database then the issue won't occur.

Steps to reproduce:

1. Start **PMAN** 
```
> pman --raw 1 --http  --port 5010 --listeners 12
```
2. In another terminal start **Django** server
```
> python manage.py runserver
```
3. `POST` to **CHRIS** to create a FS plugin
```
> http -a user:password POST http://127.0.0.1:8000/api/v1/plugins/1/instances/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json template:='{"data":[{"name":"dir","value":"./"}]}'
```
4. Stop **PMAN**
```
> <ctrl>c
```
5. Restart **PMAN**
```
>  pman --raw 1 --http  --port 5010 --listeners 12
```
6. `GET` to **CHRIS** to get the FS plugin instance that was just created
```
> http -a user:password http://127.0.0.1:8000/api/v1/plugins/instances/9/ 
```

Client message after 6.
```
HTTP/1.0 500 Internal Server Error
Content-Type: application/vnd.collection+json
Date: Wed, 15 Mar 2017 16:52:34 GMT
Server: WSGIServer/0.2 CPython/3.5.2
X-Frame-Options: SAMEORIGIN

{
    "collection": {
        "error": {
            "message": "Internal server error"
        },
        "href": "http://127.0.0.1:8000/api/v1/plugins/instances/9/",
        "version": "1.0"
    }
}
```

Server side message after 6.
```
list index out of range
[15/Mar/2017 12:52:34] "GET /api/v1/plugins/instances/9/ HTTP/1.1" 500 135
```

**Comment by NicolasRannou** [comment]
Do you have the exact commands you typed around @jbernal0019 ?

Also the server message mentions an error on "POST" - is it correct or do we actually have 2 issues?
1. `PORT` + restart **PMAN** +`GET`
2. start **PMAN** + start **CHRIS** + restart**PMAN** + `POST`

**Comment by jbernal0019** [comment]
I 've detailed the issue @NicolasRannou

**Comment by NicolasRannou** [comment]
Thanks @jbernal0019

**Comment by rudolphpienaar** [comment]
Fixed.

Actually, it wasn't really an "error" per se, but was caused by a component in 'charm' crashing.

Note: this is not really starting and restarting 'pman' per se, but is triggered by looking up an instance jid that is not in the pman database. This can happen because the pman database is not saved before the parent pman is killed, or simply by deleting the whole pman database and then trying to find data on a previous job.

Fix was to wrap the charm line in a try/except clause.
