### ISSUE TITLE
K8s: Storage resources

### ISSUE THREAD

**Issue by mamurak** [FNNDSC/ChRIS_ultron_backEnd#280]
**Background**
A number of backend services rely on data persistence, which is currently given by volume mounting as specified in the `docker-compose` file.

**Issue**
The current [Kubernetes deployment](https://github.com/FNNDSC/CHRIS_docs/pull/6) does not include any storage resources, which may be critical to databases and other services relying on data persistence.

**Task**
Add storage resources to the Kubernetes deployment for consumption by dependent services.

**Notes**
Details:
* [Kubernetes storage resources](https://kubernetes.io/docs/concepts/storage/),
* [Persistent volumes in Minikube](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/).

**Comment by jbernal0019** [comment]
We've added  persistent volume claims for single machine deployments (`hostPath` persistent volumes) and for multi-machine deployments (`nfs` persistent volumes). 

The only remaining issue is that `fnndsc/docker-swift-onlyone`  object storage container doesn't work with `nfs`. A separate object storage cluster operating directly on a Linux's ext4 FS would be needed. This could be achieved by simply running `fnndsc/docker-swift-onlyone` container on a dedicated Linux server (single machine obj storage cluster).
