### ISSUE TITLE
Docker image is having pudb.set_trace()

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [FNNDSC/ChRIS_ultron_backEnd#29]
As of now, the line https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/master/chris_backend/plugins/services/charm.py#L609 is invoking pudb because of which CI is stalling for 10 min and  timing out. Is this something intended?

cc @danmcp

**Comment by danmcp** [comment]
@rudolphpienaar @jbernal0019 Any idea on this one?

**Comment by rudolphpienaar** [comment]
Sorry guys - - my bad. A misplaced commit in the wrong repo. I'll fix.

**Comment by ravisantoshgudimetla** [comment]
Closing this as it has addressed.
