### ISSUE TITLE
API for plugin registration

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#331]
Currently, plugins can only be uploaded via

1. an HTML-based `/chris-admin/` dashboard (is not CLI friendly)
2. running the command `python plugins/services/manager.py` inside of the CUBE container (is restricted)

We need to support a way of registering plugins via a web endpoint.

Using this feature, our helper scripts for setting up ChRIS workflows could be generalized (i.e. writing `curl http://localhost:8000/api/v1/admin/plugins/ --data pl-dircopy` instead of `docker-compose -f docker-compose_dev.yml exec python plugins/services/manager.py`).

With this feature we could explore an additional feature in the [ChRIS_store_ui](https://github.com/fnndsc/chris_store_ui) where the "Add to ChRIS" button goes directly to an admin dashboard (where its URL is a ChRIS_store user account preference) with its field pre-populated, or via a cross-site request that registers the plugin without leaving the ChRIS_store_ui.

**Comment by jbernal0019** [comment]
Seems to me like not a great idea making the ChRIS store aware of the platforms that use it. And as such making it more complex by giving it additional requirements that are not directly related to its functionality (which is provide a curated list of containerized apps and a JSON description for those apps).

Also you can only register plugins into a ChRIS instance if you are an admin of that instance. Therefore the majority of ChRIS store users won't be able to use this feature. Especially anonymous unauthenticated users. Also a ChRIS admin should be able to just run `plugins/services/manager.py` from the CLI and not even have a ChRIS store account.

Keep in mind that the ChRIS store is a platform that has value independently of ChRIS. A lot of people would just want to look up apps there and run them from the CLI. Also there could be platforms totally different from ChRIS (different API) that could use the ChRIS store too. 

I would rather think about creating a new UI for ChRIS admins or improve the ChRIS admin site to be able to browse the ChRIS store directly from there and have the “Add to ChRIS” button. A ChRIS admin could register many ChRIS stores with a ChRIS instance and be able to browse them from the ChRIS admin or so. This is similar to adding a new source repo in Linux.

**Comment by jbernal0019** [comment]
To be clear even when I oppose making the ChRIS store aware of the platforms that use it I do agree with "We need to support a way of registering plugins via a web endpoint".  I think all that needs to be done is adding a new JSON view to the ChRIS admin site that accepts a POST request with a JSON content `url: <ChRIS store plugin url>`.  The view code then will register the plugin or return error code.

**Comment by rudolphpienaar** [comment]
+1 :-)

**Comment by jbernal0019** [comment]
@jennydaman @rudolphpienaar A new ChRIS admin API has beed added to CUBE that can be used to register plugins by ChRIS admins. The API is referenced  by the link relation _admin_ in the CUBE API homepage (user's list of feeds) and the current url is `chris-admin/api/v1/`

So a ChRIS admin can do something like this to register a plugin through the new API:

`http -a chris:chris1234 POST http://localhost:8000/chris-admin/api/v1/ plugin_store_url=http://chris-store.local:8010/api/v1/plugins/17/ compute_name=host  Accept:application/vnd.collection+json`

Ideally a client should first fetch the url of the new API from `http://localhost:8000/chris-admin/api/v1/ ` using the _admin_ link relation as this url can easily change in the future and break the client.

**Comment by jbernal0019** [comment]
Oh! I've just realized that I need to add another endpoint to the new API to be able to first add a compute resource like `host` or `moc` for instance. The url would be `http://localhost:8000/chris-admin/api/v1/computeresources/`
