### ISSUE TITLE
Large datasets in plugin instances

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#369]
I am having problems with "large" datasets in plugin instances (5GiB). I created a plugin to demonstrate the problems:

https://chrisstore.co/plugin/dbg-bigfiles

If you run this _fs_ plugin without arguments, it creates files thousands of files each 2MiB in size, totaling to 5GiB. pfcon is unable to handle send the zip back to CUBE.

```
[ERROR][manager 9 140593460442944] [CODE03,chris-jid-1]: Error fetching zip from pfcon url -->http://pfcon.host:5005/api/v1/<--, detail: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by jbernal0019** [comment]
Fixed in latest release. Basically the file response for the zip file was changed in `pfcon`.
