### ISSUE TITLE
Replace string regex with compiled regex

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#383]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/3ee492dfa699b6394b19a6458fd511bda2824e09/chris_backend/plugins/serializers.py#L135

**Comment by fortune-max** [comment]
Hi @jennydaman , please could I be assigned this issue to get a bit comfortable with the project?

**Comment by fortune-max** [comment]
<img width="637" alt="Screenshot 2022-04-17 at 16 21 05" src="https://user-images.githubusercontent.com/31856097/163720978-7f82069f-5ad8-4b94-8999-81177c51f0dc.png">

Please could you look over this? Can I open a PR?

**Comment by fortune-max** [comment]
Just thought about it, and if the intention is to reduce how often the Pattern is generated (before being matched) it may be better to make `re_valid_version` a class/not-a-local variable. Let me know your thoughts on this.

**Comment by fortune-max** [comment]
I am now fairly comfortable with the project and have poked around a bit. Very interesting project both on the technical side as well as the objectives aimed at.

I am now looking at this [issue](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/382). Please have a look when you can.

**Comment by fortune-max** [comment]
Pull request [here](https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/387).

**Comment by sakshi1215** [comment]
Hi @jennydaman I am an outreachy candidate can you please assign this issue to me?

**Comment by sakshi1215** [comment]
Ping @jennydaman if you missed the following 😄

**Comment by jennydaman** [comment]
@Aman-Jamshed due to inactivity, I have reassigned this issue to @sakshi1215
