### ISSUE TITLE
Env support CUBE/pfcon/pman

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ultron_backEnd#428]

**Comment by kibablu** [comment]
@rudolphpienaar would love to know more about how CUBE will support pfcon. A google search found you're also the maintainer https://pypi.org/project/pfcon/

**Comment by jennydaman** [comment]
Fixed in https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/432
