### ISSUE TITLE
Kubernetes pman service account

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#447]
pman cannot schedule jobs using the Kubernetes API without special permissions to the service account it uses.

https://github.com/FNNDSC/pman/tree/f91e7b7ee482bd265d37e15a58f9f0fad279d840/kubernetes/prod/extra

**Comment by vareenrose** [comment]
Hi @jennydaman how can I recreate this error

**Comment by jennydaman** [comment]
Closed by https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/449
