### ISSUE TITLE
Expose API to anonymous users

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#452]
Feature request: it should be possible to browse global APIs, such as `/api/v1/plugins/` and `/api/v1/pipeines/` without having to provide authentication.

**Comment by Barissa-Imran** [comment]
Hi @jennydaman I would like to be assigned this issue

**Comment by dipanshuraz** [comment]
Hi @jennydaman I'm interested to work on this, If possible we can pick this up together @Barissa-Imran 👍
