### ISSUE TITLE
Fix lint errors across modules

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#458]
chris_backend defies a lot of pep8 rules. The code requires a lot of improvement on the linting side. 
`autopep8` fixes only a bunch of them. The code rating is `5.64/10` as per the `pylint **/*.py` command. This issue tracks down all the modules that require refactoring. 
The following is the modules breakup which require work.

- [ ] [Module manage](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/468)
- [ ] [Module migratedb](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/467)
- [ ] [Module collectionjson](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/459)
- [ ] [Module config](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/460)
- [ ] [Module plugininstances](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/461)
- [ ] [Module plugins](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/462)
- [ ] [Module servicefiles](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/463)
- [ ] [Module uploadedfiles](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/464)
- [ ] [Module users](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/465)
- [ ] [Module workflows](https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/466)

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by zannybobo02** [comment]
Hello, I am John Asobi an applicant for the outreachy internship, I will love to take on this issue. Please can it be assigned to me
