### ISSUE TITLE
Fix lint errors in module: Collectionjson

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#459]
Following is the output of `pylint collectionjson/*py`
************* Module collectionjson.admin
collectionjson/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
collectionjson/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module collectionjson.apps
collectionjson/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
collectionjson/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
collectionjson/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module collectionjson.fields
collectionjson/fields.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/fields.py:2:0: E0401: Unable to import 'rest_framework.fields' (import-error)
collectionjson/fields.py:5:0: C0115: Missing class docstring (missing-class-docstring)
collectionjson/fields.py:6:4: W0246: Useless parent or super() delegation in method '__init__' (useless-parent-delegation)
collectionjson/fields.py:7:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
collectionjson/fields.py:5:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module collectionjson.models
collectionjson/models.py:5:0: C0305: Trailing newlines (trailing-newlines)
collectionjson/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/models.py:2:0: W0611: Unused Dummy imported from collectionjson.tests.models (unused-import)
collectionjson/models.py:2:0: W0611: Unused Idiot imported from collectionjson.tests.models (unused-import)
collectionjson/models.py:2:0: W0611: Unused Moron imported from collectionjson.tests.models (unused-import)
collectionjson/models.py:2:0: W0611: Unused Simple imported from collectionjson.tests.models (unused-import)
************* Module collectionjson.parsers
collectionjson/parsers.py:20:46: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/parsers.py:21:40: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/parsers.py:25:40: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/parsers.py:27:24: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/parsers.py:34:0: C0305: Trailing newlines (trailing-newlines)
collectionjson/parsers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/parsers.py:1:0: E0401: Unable to import 'rest_framework.parsers' (import-error)
collectionjson/parsers.py:2:0: E0401: Unable to import 'rest_framework.exceptions' (import-error)
collectionjson/parsers.py:4:0: C0115: Missing class docstring (missing-class-docstring)
collectionjson/parsers.py:7:4: C0116: Missing function or method docstring (missing-function-docstring)
collectionjson/parsers.py:17:16: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
collectionjson/parsers.py:19:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
collectionjson/parsers.py:20:21: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
collectionjson/parsers.py:22:12: W0707: Consider explicitly re-raising using 'raise ParseError(detail=detail) from e' (raise-missing-from)
collectionjson/parsers.py:23:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
collectionjson/parsers.py:26:12: W0707: Consider explicitly re-raising using 'raise ParseError(detail=detail) from e' (raise-missing-from)
collectionjson/parsers.py:23:8: W0612: Unused variable 'e' (unused-variable)
collectionjson/parsers.py:29:4: C0116: Missing function or method docstring (missing-function-docstring)
collectionjson/parsers.py:30:22: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module collectionjson.renderers
collectionjson/renderers.py:35:58: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/renderers.py:122:0: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/renderers.py:130:0: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/renderers.py:137:0: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/renderers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/renderers.py:4:0: E0401: Unable to import 'rest_framework.serializers' (import-error)
collectionjson/renderers.py:6:0: E0401: Unable to import 'rest_framework.renderers' (import-error)
collectionjson/renderers.py:12:0: C0115: Missing class docstring (missing-class-docstring)
collectionjson/renderers.py:24:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
collectionjson/renderers.py:34:21: R1701: Consider merging these isinstance calls to isinstance(v, (HyperlinkedIdentityField, HyperlinkedRelatedField, ItemLinkField)) (consider-merging-isinstance)
collectionjson/renderers.py:46:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
collectionjson/renderers.py:67:12: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
collectionjson/renderers.py:79:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
collectionjson/renderers.py:120:12: C0103: Variable name "l" doesn't conform to snake_case naming style (invalid-name)
collectionjson/renderers.py:138:4: C0116: Missing function or method docstring (missing-function-docstring)
collectionjson/renderers.py:163:4: C0116: Missing function or method docstring (missing-function-docstring)
collectionjson/renderers.py:171:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
************* Module collectionjson.serializers
collectionjson/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/serializers.py:2:0: E0401: Unable to import 'rest_framework' (import-error)
collectionjson/serializers.py:5:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module collectionjson.services
collectionjson/services.py:31:0: C0303: Trailing whitespace (trailing-whitespace)
collectionjson/services.py:76:0: C0304: Final newline missing (missing-final-newline)
collectionjson/services.py:1:0: C0114: Missing module docstring (missing-module-docstring)
collectionjson/services.py:4:0: E0401: Unable to import 'django.urls' (import-error)
collectionjson/services.py:6:0: E0401: Unable to import 'rest_framework.response' (import-error)
collectionjson/services.py:7:0: E0401: Unable to import 'rest_framework' (import-error)
collectionjson/services.py:42:12: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)

-----------------------------------
Your code has been rated at 4.04/10

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
