### ISSUE TITLE
Fix lint errors across module: config

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#460]
Following is the output of `pylint config/*py`

************ Module config.asgi
config/asgi.py:10:0: C0410: Multiple imports on one line (os, sys) (multiple-imports)
config/asgi.py:13:0: E0401: Unable to import 'django.core.asgi' (import-error)
config/asgi.py:13:0: C0413: Import "from django.core.asgi import get_asgi_application" should be placed at the top of the module (wrong-import-position)
************* Module config.urls
config/urls.py:17:0: E0401: Unable to import 'django.contrib' (import-error)
config/urls.py:18:0: E0401: Unable to import 'django.urls' (import-error)
config/urls.py:19:0: E0401: Unable to import 'django.conf' (import-error)
config/urls.py:39:4: E0401: Unable to import 'debug_toolbar' (import-error)
************* Module config.wsgi
config/wsgi.py:10:0: C0410: Multiple imports on one line (os, sys) (multiple-imports)
config/wsgi.py:13:0: E0401: Unable to import 'django.core.wsgi' (import-error)
config/wsgi.py:13:0: C0413: Import "from django.core.wsgi import get_wsgi_application" should be placed at the top of the module (wrong-import-position)

-----------------------------------
Your code has been rated at 0.00/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
