### ISSUE TITLE
Fix lint errors across module: plugininstances

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#461]
Following is the output of `pylint plugininstances/*py`

************ Module plugininstances.admin
plugininstances/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
plugininstances/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module plugininstances.apps
plugininstances/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
plugininstances/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module plugininstances.models
plugininstances/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/models.py:4:0: E0401: Unable to import 'django.db' (import-error)
plugininstances/models.py:5:0: E0401: Unable to import 'django.conf' (import-error)
plugininstances/models.py:7:0: E0401: Unable to import 'django_filters' (import-error)
plugininstances/models.py:8:0: E0401: Unable to import 'django_filters.rest_framework' (import-error)
plugininstances/models.py:19:4: C0410: Multiple imports on one line (pdb, pudb) (multiple-imports)
plugininstances/models.py:19:4: E0401: Unable to import 'pudb' (import-error)
plugininstances/models.py:35:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:64:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:64:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:82:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/models.py:141:15: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugininstances/models.py:144:19: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugininstances/models.py:148:22: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugininstances/models.py:166:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:191:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:191:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:198:42: W0613: Unused argument 'name' (unused-argument)
plugininstances/models.py:166:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:216:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:216:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:224:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:231:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:231:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:224:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:238:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:244:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:244:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:238:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:251:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:266:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:266:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:271:44: W0613: Unused argument 'name' (unused-argument)
plugininstances/models.py:251:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:281:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:288:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:288:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:281:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:295:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:302:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:302:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:295:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:309:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:316:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:316:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:309:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:323:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:330:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:330:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:323:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:337:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:344:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:344:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:337:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:351:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:358:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/models.py:358:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/models.py:351:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/models.py:19:4: W0611: Unused import pdb (unused-import)
plugininstances/models.py:19:4: W0611: Unused import pudb (unused-import)
************* Module plugininstances.permissions
plugininstances/permissions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/permissions.py:1:0: E0401: Unable to import 'rest_framework' (import-error)
plugininstances/permissions.py:10:4: C0116: Missing function or method docstring (missing-function-docstring)
plugininstances/permissions.py:10:45: W0613: Unused argument 'view' (unused-argument)
plugininstances/permissions.py:4:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/permissions.py:30:4: C0116: Missing function or method docstring (missing-function-docstring)
plugininstances/permissions.py:30:45: W0613: Unused argument 'view' (unused-argument)
plugininstances/permissions.py:24:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/permissions.py:46:4: C0116: Missing function or method docstring (missing-function-docstring)
plugininstances/permissions.py:46:45: W0613: Unused argument 'view' (unused-argument)
plugininstances/permissions.py:40:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module plugininstances.serializers
plugininstances/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/serializers.py:5:0: E0401: Unable to import 'django.core.exceptions' (import-error)
plugininstances/serializers.py:6:0: E0401: Unable to import 'django.conf' (import-error)
plugininstances/serializers.py:7:0: E0401: Unable to import 'rest_framework' (import-error)
plugininstances/serializers.py:8:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
plugininstances/serializers.py:24:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:68:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:68:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:101:16: C0103: Variable name "pk" doesn't conform to snake_case naming style (invalid-name)
plugininstances/serializers.py:105:16: W0707: Consider explicitly re-raising using 'except (ValueError, ObjectDoesNotExist) as exc' and 'raise serializers.ValidationError({'previous_id': [err_str % previous_id]}) from exc' (raise-missing-from)
plugininstances/serializers.py:122:18: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugininstances/serializers.py:180:4: C0116: Missing function or method docstring (missing-function-docstring)
plugininstances/serializers.py:185:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:193:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:193:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:215:47: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
plugininstances/serializers.py:227:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:236:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:236:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:227:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/serializers.py:248:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:256:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:256:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:268:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/serializers.py:287:24: W0707: Consider explicitly re-raising using 'except (ValueError, ObjectDoesNotExist) as exc' and 'raise serializers.ValidationError([f"Couldn't find any plugin instance with id '{inst_id}'."]) from exc' (raise-missing-from)
plugininstances/serializers.py:248:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/serializers.py:299:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:307:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:307:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:299:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:313:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:321:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:321:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:313:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:327:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:335:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:335:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:327:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:365:16: W0707: Consider explicitly re-raising using 'except (ValueError, Feed.DoesNotExist) as exc' and 'raise serializers.ValidationError(['This field may not be an invalid path.']) from exc' (raise-missing-from)
plugininstances/serializers.py:374:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugininstances/serializers.py:375:16: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
plugininstances/serializers.py:375:29: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugininstances/serializers.py:384:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:392:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:392:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:402:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/serializers.py:384:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/serializers.py:413:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:421:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:421:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:431:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/serializers.py:413:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/serializers.py:442:0: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:452:4: C0115: Missing class docstring (missing-class-docstring)
plugininstances/serializers.py:452:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/serializers.py:442:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module plugininstances.tasks
plugininstances/tasks.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/tasks.py:112:0: W0622: Redefining built-in 'sum' (redefined-builtin)
plugininstances/tasks.py:5:0: E0401: Unable to import 'django.db.models' (import-error)
plugininstances/tasks.py:7:0: E0401: Unable to import 'celery' (import-error)
plugininstances/tasks.py:16:20: C0103: Argument name "f" doesn't conform to snake_case naming style (invalid-name)
plugininstances/tasks.py:74:38: W0613: Unused argument 'self' (unused-argument)
plugininstances/tasks.py:112:0: C0116: Missing function or method docstring (missing-function-docstring)
plugininstances/tasks.py:112:8: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
plugininstances/tasks.py:112:11: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
************* Module plugininstances.utils
plugininstances/utils.py:22:0: C0305: Trailing newlines (trailing-newlines)
plugininstances/utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module plugininstances.views
plugininstances/views.py:44:85: C0303: Trailing whitespace (trailing-whitespace)
plugininstances/views.py:45:87: C0303: Trailing whitespace (trailing-whitespace)
plugininstances/views.py:155:0: C0303: Trailing whitespace (trailing-whitespace)
plugininstances/views.py:471:0: C0303: Trailing whitespace (trailing-whitespace)
plugininstances/views.py:491:0: C0303: Trailing whitespace (trailing-whitespace)
plugininstances/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugininstances/views.py:2:0: E0401: Unable to import 'django.http' (import-error)
plugininstances/views.py:3:0: E0401: Unable to import 'rest_framework' (import-error)
plugininstances/views.py:4:0: E0401: Unable to import 'rest_framework' (import-error)
plugininstances/views.py:5:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
plugininstances/views.py:6:0: E0401: Unable to import 'rest_framework.serializers' (import-error)
plugininstances/views.py:40:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:42:4: R0914: Too many local variables (17/15) (too-many-locals)
plugininstances/views.py:91:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:91:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:136:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:123:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/views.py:145:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:169:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:183:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:199:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:215:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:228:19: W0613: Unused argument 'request' (unused-argument)
plugininstances/views.py:228:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:228:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:273:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
plugininstances/views.py:292:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:292:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:317:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:336:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:336:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:372:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugininstances/views.py:389:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/views.py:411:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:430:18: W0613: Unused argument 'request' (unused-argument)
plugininstances/views.py:430:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:430:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:421:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugininstances/views.py:447:19: W0613: Unused argument 'request' (unused-argument)
plugininstances/views.py:447:0: W0613: Unused argument 'args' (unused-argument)
plugininstances/views.py:447:0: W0613: Unused argument 'kwargs' (unused-argument)
plugininstances/views.py:463:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:473:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:483:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:493:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:503:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:513:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugininstances/views.py:21:0: W0611: Unused run_plugin_instance imported from tasks (unused-import)

-----------------------------------
Your code has been rated at 6.69/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
