### ISSUE TITLE
Fix lint errors across module: pluginins

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#462]
Following is the output of `pylint plugins/*py`

************* Module plugins.admin
plugins/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/admin.py:2:0: E0401: Unable to import 'django.contrib' (import-error)
plugins/admin.py:3:0: E0401: Unable to import 'django.utils' (import-error)
plugins/admin.py:4:0: E0401: Unable to import 'django.urls' (import-error)
plugins/admin.py:5:0: E0401: Unable to import 'django.shortcuts' (import-error)
plugins/admin.py:6:0: E0401: Unable to import 'django' (import-error)
plugins/admin.py:7:0: E0401: Unable to import 'django.core.validators' (import-error)
plugins/admin.py:8:0: E0401: Unable to import 'django.core.exceptions' (import-error)
plugins/admin.py:9:0: E0401: Unable to import 'django.contrib' (import-error)
plugins/admin.py:10:0: E0401: Unable to import 'rest_framework' (import-error)
plugins/admin.py:11:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
plugins/admin.py:20:46: W0212: Access to a protected member _meta of a client class (protected-access)
plugins/admin.py:24:0: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:64:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:68:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
plugins/admin.py:34:8: W0201: Attribute 'fields' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:43:8: W0201: Attribute 'fields' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:86:0: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:94:36: W0613: Unused argument 'request' (unused-argument)
plugins/admin.py:94:45: W0613: Unused argument 'obj' (unused-argument)
plugins/admin.py:100:33: W0613: Unused argument 'request' (unused-argument)
plugins/admin.py:107:0: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:107:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/admin.py:111:0: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:127:12: C0103: Variable name "cr" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:131:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:141:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:121:11: E0203: Access to member 'instance' before its definition line 130 (access-member-before-definition)
plugins/admin.py:130:20: W0201: Attribute 'instance' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:140:20: W0201: Attribute 'instance' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:111:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/admin.py:152:0: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:176:31: R1721: Unnecessary use of a comprehension, use list(plugin_readonly_fields) instead. (unnecessary-comprehension)
plugins/admin.py:194:4: C0116: Missing function or method docstring (missing-function-docstring)
plugins/admin.py:195:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/admin.py:252:41: C0103: Argument name "f" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:286:27: W0703: Catching too general exception Exception (broad-except)
plugins/admin.py:286:20: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:296:27: W0703: Catching too general exception Exception (broad-except)
plugins/admin.py:296:20: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:164:8: W0201: Attribute 'readonly_fields' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:176:8: W0201: Attribute 'readonly_fields' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:165:8: W0201: Attribute 'fieldsets' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:178:8: W0201: Attribute 'fieldsets' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:318:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/admin.py:303:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/admin.py:339:4: C0115: Missing class docstring (missing-class-docstring)
plugins/admin.py:339:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/admin.py:353:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/admin.py:352:12: W0201: Attribute 'instance' defined outside __init__ (attribute-defined-outside-init)
plugins/admin.py:373:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/admin.py:358:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module plugins.apps
plugins/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
plugins/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
plugins/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module plugins.fields
plugins/fields.py:45:0: C0301: Line too long (103/100) (line-too-long)
plugins/fields.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/fields.py:2:0: E0401: Unable to import 'django.db' (import-error)
plugins/fields.py:3:0: E0401: Unable to import 'django.core.exceptions' (import-error)
plugins/fields.py:6:0: C0115: Missing class docstring (missing-class-docstring)
plugins/fields.py:27:12: W0707: Consider explicitly re-raising using 'except (IndexError, ValueError, AssertionError) as exc' and 'raise ValueError('Memory format incorrect. Format is xMi or xGi where x is an integer.') from exc' (raise-missing-from)
plugins/fields.py:7:0: W0613: Unused argument 'args' (unused-argument)
plugins/fields.py:7:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/fields.py:31:0: C0115: Missing class docstring (missing-class-docstring)
plugins/fields.py:45:12: W0707: Consider explicitly re-raising using 'except (IndexError, ValueError, AssertionError) as exc' and 'raise ValueError('CPU format incorrect. Format is xm where x is an integer in millicores.') from exc' (raise-missing-from)
plugins/fields.py:32:0: W0613: Unused argument 'args' (unused-argument)
plugins/fields.py:32:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/fields.py:53:4: C0116: Missing function or method docstring (missing-function-docstring)
plugins/fields.py:69:12: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValidationError(self.error_message) from exc' (raise-missing-from)
plugins/fields.py:76:4: C0116: Missing function or method docstring (missing-function-docstring)
plugins/fields.py:92:12: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValidationError(self.error_message) from exc' (raise-missing-from)
************* Module plugins.models
plugins/models.py:264:0: C0303: Trailing whitespace (trailing-whitespace)
plugins/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/models.py:2:0: E0401: Unable to import 'django.db' (import-error)
plugins/models.py:4:0: E0401: Unable to import 'django_filters' (import-error)
plugins/models.py:5:0: E0401: Unable to import 'django_filters.rest_framework' (import-error)
plugins/models.py:6:0: E0401: Unable to import 'django.core.exceptions' (import-error)
plugins/models.py:51:0: W0613: Unused argument 'args' (unused-argument)
plugins/models.py:51:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/models.py:83:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:83:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:72:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:106:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:106:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:88:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:131:51: W0613: Unused argument 'name' (unused-argument)
plugins/models.py:142:53: W0613: Unused argument 'name' (unused-argument)
plugins/models.py:153:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:153:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:193:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:193:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:206:4: C0116: Missing function or method docstring (missing-function-docstring)
plugins/models.py:232:51: W0613: Unused argument 'name' (unused-argument)
plugins/models.py:243:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:243:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:212:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:265:4: C0115: Missing class docstring (missing-class-docstring)
plugins/models.py:265:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/models.py:275:28: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugins/models.py:279:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:291:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:303:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:315:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/models.py:6:0: C0412: Imports from package django are not grouped (ungrouped-imports)
************* Module plugins.serializers
plugins/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/serializers.py:4:0: E0401: Unable to import 'django.utils' (import-error)
plugins/serializers.py:5:0: E0401: Unable to import 'rest_framework' (import-error)
plugins/serializers.py:13:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:20:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:20:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:13:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:28:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:31:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:31:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:43:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/serializers.py:28:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/serializers.py:46:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:64:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:64:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:136:47: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
plugins/serializers.py:158:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/serializers.py:168:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
plugins/serializers.py:188:12: W0707: Consider explicitly re-raising using 'except (ValueError, AssertionError) as exc' and 'raise serializers.ValidationError({descriptor_dict['name']: [error_msg]}) from exc' (raise-missing-from)
plugins/serializers.py:202:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:207:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:207:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:232:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:238:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:238:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:232:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:243:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:249:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:249:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:243:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:254:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:260:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:260:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:254:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:265:0: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:271:4: C0115: Missing class docstring (missing-class-docstring)
plugins/serializers.py:271:4: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/serializers.py:265:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module plugins.views
plugins/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
plugins/views.py:2:0: E0401: Unable to import 'rest_framework' (import-error)
plugins/views.py:3:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
plugins/views.py:27:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/views.py:13:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/views.py:36:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:47:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:71:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/views.py:57:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/views.py:81:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:92:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:111:0: W0613: Unused argument 'args' (unused-argument)
plugins/views.py:111:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/views.py:145:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
plugins/views.py:131:0: R0903: Too few public methods (1/2) (too-few-public-methods)
plugins/views.py:155:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:175:0: W0613: Unused argument 'args' (unused-argument)
plugins/views.py:175:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/views.py:195:0: R0903: Too few public methods (0/2) (too-few-public-methods)
plugins/views.py:214:0: W0613: Unused argument 'args' (unused-argument)
plugins/views.py:214:0: W0613: Unused argument 'kwargs' (unused-argument)
plugins/views.py:234:0: R0903: Too few public methods (0/2) (too-few-public-methods)

-----------------------------------
Your code has been rated at 6.41/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
