### ISSUE TITLE
Fix lint errors across module: servicefiles

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#463]
Following is the output of `pylint servicefiles/*py`

************* Module servicefiles.admin
servicefiles/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
servicefiles/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module servicefiles.apps
servicefiles/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
servicefiles/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module servicefiles.models
servicefiles/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/models.py:2:0: E0401: Unable to import 'django.db' (import-error)
servicefiles/models.py:3:0: E0401: Unable to import 'django_filters' (import-error)
servicefiles/models.py:4:0: E0401: Unable to import 'django_filters.rest_framework' (import-error)
servicefiles/models.py:12:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/models.py:12:0: R0903: Too few public methods (1/2) (too-few-public-methods)
servicefiles/models.py:19:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/models.py:24:4: C0115: Missing class docstring (missing-class-docstring)
servicefiles/models.py:24:4: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/models.py:19:0: R0903: Too few public methods (1/2) (too-few-public-methods)
servicefiles/models.py:31:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/models.py:45:4: C0115: Missing class docstring (missing-class-docstring)
servicefiles/models.py:45:4: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/models.py:50:44: W0613: Unused argument 'name' (unused-argument)
servicefiles/models.py:31:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module servicefiles.permissions
servicefiles/permissions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/permissions.py:2:0: E0401: Unable to import 'rest_framework' (import-error)
servicefiles/permissions.py:11:4: C0116: Missing function or method docstring (missing-function-docstring)
servicefiles/permissions.py:11:38: W0613: Unused argument 'view' (unused-argument)
servicefiles/permissions.py:5:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module servicefiles.serializers
servicefiles/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/serializers.py:4:0: E0401: Unable to import 'django.conf' (import-error)
servicefiles/serializers.py:5:0: E0401: Unable to import 'rest_framework' (import-error)
servicefiles/serializers.py:18:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/serializers.py:20:4: C0115: Missing class docstring (missing-class-docstring)
servicefiles/serializers.py:20:4: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/serializers.py:18:0: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/serializers.py:25:0: C0115: Missing class docstring (missing-class-docstring)
servicefiles/serializers.py:33:4: C0115: Missing class docstring (missing-class-docstring)
servicefiles/serializers.py:33:4: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/serializers.py:51:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
servicefiles/serializers.py:69:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
servicefiles/serializers.py:83:17: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
servicefiles/serializers.py:85:24: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
servicefiles/serializers.py:92:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
servicefiles/serializers.py:93:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
servicefiles/serializers.py:93:25: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
servicefiles/serializers.py:106:18: C0103: Variable name "tf" doesn't conform to snake_case naming style (invalid-name)
servicefiles/serializers.py:106:18: W0612: Unused variable 'tf' (unused-variable)
************* Module servicefiles.views
servicefiles/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
servicefiles/views.py:2:0: E0401: Unable to import 'django.http' (import-error)
servicefiles/views.py:3:0: E0401: Unable to import 'rest_framework' (import-error)
servicefiles/views.py:4:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
servicefiles/views.py:28:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
servicefiles/views.py:41:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
servicefiles/views.py:44:0: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/views.py:55:0: R0903: Too few public methods (0/2) (too-few-public-methods)
servicefiles/views.py:74:18: W0613: Unused argument 'request' (unused-argument)
servicefiles/views.py:74:0: W0613: Unused argument 'args' (unused-argument)
servicefiles/views.py:74:0: W0613: Unused argument 'kwargs' (unused-argument)
servicefiles/views.py:65:0: R0903: Too few public methods (1/2) (too-few-public-methods)

-----------------------------------
Your code has been rated at 3.15/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
