### ISSUE TITLE
Fix lint errors across module: uploadedfiles

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#464]
Following is the output of `pylint uploadedfiles/*py`

************* Module uploadedfiles.admin
uploadedfiles/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
uploadedfiles/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module uploadedfiles.apps
uploadedfiles/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
uploadedfiles/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module uploadedfiles.models
uploadedfiles/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/models.py:2:0: E0401: Unable to import 'django.db' (import-error)
uploadedfiles/models.py:3:0: E0401: Unable to import 'django_filters' (import-error)
uploadedfiles/models.py:4:0: E0401: Unable to import 'django_filters.rest_framework' (import-error)
uploadedfiles/models.py:9:0: C0116: Missing function or method docstring (missing-function-docstring)
uploadedfiles/models.py:9:33: W0613: Unused argument 'filename' (unused-argument)
uploadedfiles/models.py:15:0: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/models.py:20:4: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/models.py:20:4: R0903: Too few public methods (0/2) (too-few-public-methods)
uploadedfiles/models.py:15:0: R0903: Too few public methods (1/2) (too-few-public-methods)
uploadedfiles/models.py:27:0: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/models.py:42:4: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/models.py:42:4: R0903: Too few public methods (0/2) (too-few-public-methods)
uploadedfiles/models.py:47:44: W0613: Unused argument 'name' (unused-argument)
uploadedfiles/models.py:65:8: C0103: Variable name "qs" doesn't conform to snake_case naming style (invalid-name)
uploadedfiles/models.py:67:12: C0103: Variable name "qs" doesn't conform to snake_case naming style (invalid-name)
uploadedfiles/models.py:56:53: W0613: Unused argument 'name' (unused-argument)
************* Module uploadedfiles.permissions
uploadedfiles/permissions.py:17:0: C0305: Trailing newlines (trailing-newlines)
uploadedfiles/permissions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/permissions.py:1:0: E0401: Unable to import 'rest_framework' (import-error)
uploadedfiles/permissions.py:10:4: C0116: Missing function or method docstring (missing-function-docstring)
uploadedfiles/permissions.py:10:45: W0613: Unused argument 'view' (unused-argument)
uploadedfiles/permissions.py:4:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module uploadedfiles.serializers
uploadedfiles/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/serializers.py:2:0: E0401: Unable to import 'rest_framework' (import-error)
uploadedfiles/serializers.py:10:0: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/serializers.py:17:4: C0115: Missing class docstring (missing-class-docstring)
uploadedfiles/serializers.py:17:4: R0903: Too few public methods (0/2) (too-few-public-methods)
uploadedfiles/serializers.py:35:17: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
uploadedfiles/serializers.py:37:24: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
************* Module uploadedfiles.views
uploadedfiles/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
uploadedfiles/views.py:4:0: E0401: Unable to import 'django.conf' (import-error)
uploadedfiles/views.py:5:0: E0401: Unable to import 'django.http' (import-error)
uploadedfiles/views.py:6:0: E0401: Unable to import 'rest_framework' (import-error)
uploadedfiles/views.py:7:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
uploadedfiles/views.py:46:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
uploadedfiles/views.py:55:0: R0903: Too few public methods (0/2) (too-few-public-methods)
uploadedfiles/views.py:79:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
uploadedfiles/views.py:89:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
uploadedfiles/views.py:102:15: W0703: Catching too general exception Exception (broad-except)
uploadedfiles/views.py:102:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
uploadedfiles/views.py:103:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
uploadedfiles/views.py:103:25: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
uploadedfiles/views.py:115:15: W0703: Catching too general exception Exception (broad-except)
uploadedfiles/views.py:115:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
uploadedfiles/views.py:116:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
uploadedfiles/views.py:116:25: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
uploadedfiles/views.py:128:18: W0613: Unused argument 'request' (unused-argument)
uploadedfiles/views.py:128:0: W0613: Unused argument 'args' (unused-argument)
uploadedfiles/views.py:128:0: W0613: Unused argument 'kwargs' (unused-argument)
uploadedfiles/views.py:119:0: R0903: Too few public methods (1/2) (too-few-public-methods)

-----------------------------------
Your code has been rated at 2.97/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
