### ISSUE TITLE
Fix lint errors across module: users

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#465]
Following is the output of `pylint users/*py`

************* Module users.admin
users/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
users/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module users.apps
users/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
users/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
users/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module users.models
users/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/models.py:1:0: E0401: Unable to import 'django.db' (import-error)
users/models.py:1:0: W0611: Unused models imported from django.db (unused-import)
************* Module users.permissions
users/permissions.py:20:0: C0305: Trailing newlines (trailing-newlines)
users/permissions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/permissions.py:1:0: E0401: Unable to import 'rest_framework' (import-error)
users/permissions.py:10:4: C0116: Missing function or method docstring (missing-function-docstring)
users/permissions.py:10:45: W0613: Unused argument 'view' (unused-argument)
users/permissions.py:4:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module users.serializers
users/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/serializers.py:5:0: E0401: Unable to import 'django.contrib.auth.models' (import-error)
users/serializers.py:6:0: E0401: Unable to import 'django.conf' (import-error)
users/serializers.py:7:0: E0401: Unable to import 'rest_framework' (import-error)
users/serializers.py:8:0: E0401: Unable to import 'rest_framework.validators' (import-error)
users/serializers.py:17:0: C0115: Missing class docstring (missing-class-docstring)
users/serializers.py:28:4: C0115: Missing class docstring (missing-class-docstring)
users/serializers.py:28:4: R0903: Too few public methods (0/2) (too-few-public-methods)
users/serializers.py:43:28: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
users/serializers.py:51:15: W0703: Catching too general exception Exception (broad-except)
users/serializers.py:45:53: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
users/serializers.py:51:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
users/serializers.py:52:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
users/serializers.py:52:25: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
users/serializers.py:64:11: R1714: Consider merging these comparisons with 'in' by using 'username in ('chris', 'SERVICES')'. Use a set instead if elements are hashable. (consider-using-in)
users/serializers.py:66:17: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
************* Module users.views
users/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
users/views.py:2:0: E0401: Unable to import 'django.contrib.auth.models' (import-error)
users/views.py:3:0: E0401: Unable to import 'rest_framework' (import-error)
users/views.py:4:0: E0401: Unable to import 'rest_framework.response' (import-error)
users/views.py:12:0: C0115: Missing class docstring (missing-class-docstring)
users/views.py:17:19: W0613: Unused argument 'request' (unused-argument)
users/views.py:17:0: W0613: Unused argument 'args' (unused-argument)
users/views.py:17:0: W0613: Unused argument 'kwargs' (unused-argument)
users/views.py:12:0: R0903: Too few public methods (1/2) (too-few-public-methods)
users/views.py:26:0: C0115: Missing class docstring (missing-class-docstring)
users/views.py:32:23: W0613: Unused argument 'request' (unused-argument)
users/views.py:32:0: W0613: Unused argument 'args' (unused-argument)
users/views.py:32:0: W0613: Unused argument 'kwargs' (unused-argument)
users/views.py:48:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

-----------------------------------
Your code has been rated at 0.00/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
