### ISSUE TITLE
Fix lint errors across module: workflows

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#466]
Following is the output of `pylint workflows/*py`

************* Module workflows.admin
workflows/admin.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/admin.py:1:0: E0401: Unable to import 'django.contrib' (import-error)
workflows/admin.py:1:0: W0611: Unused admin imported from django.contrib (unused-import)
************* Module workflows.apps
workflows/apps.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/apps.py:1:0: E0401: Unable to import 'django.apps' (import-error)
workflows/apps.py:4:0: C0115: Missing class docstring (missing-class-docstring)
workflows/apps.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module workflows.models
workflows/models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/models.py:2:0: E0401: Unable to import 'django.db' (import-error)
workflows/models.py:3:0: E0401: Unable to import 'django_filters' (import-error)
workflows/models.py:4:0: E0401: Unable to import 'django_filters.rest_framework' (import-error)
workflows/models.py:9:0: C0115: Missing class docstring (missing-class-docstring)
workflows/models.py:16:4: C0115: Missing class docstring (missing-class-docstring)
workflows/models.py:16:4: R0903: Too few public methods (0/2) (too-few-public-methods)
workflows/models.py:9:0: R0903: Too few public methods (1/2) (too-few-public-methods)
workflows/models.py:23:0: C0115: Missing class docstring (missing-class-docstring)
workflows/models.py:30:4: C0115: Missing class docstring (missing-class-docstring)
workflows/models.py:30:4: R0903: Too few public methods (0/2) (too-few-public-methods)
workflows/models.py:23:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module workflows.permissions
workflows/permissions.py:17:0: C0304: Final newline missing (missing-final-newline)
workflows/permissions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/permissions.py:1:0: E0401: Unable to import 'rest_framework' (import-error)
workflows/permissions.py:10:4: C0116: Missing function or method docstring (missing-function-docstring)
workflows/permissions.py:10:45: W0613: Unused argument 'view' (unused-argument)
workflows/permissions.py:4:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module workflows.serializers
workflows/serializers.py:141:0: C0301: Line too long (110/100) (line-too-long)
workflows/serializers.py:148:0: C0301: Line too long (133/100) (line-too-long)
workflows/serializers.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/serializers.py:5:0: E0401: Unable to import 'django.core.exceptions' (import-error)
workflows/serializers.py:6:0: E0401: Unable to import 'rest_framework' (import-error)
workflows/serializers.py:15:0: C0115: Missing class docstring (missing-class-docstring)
workflows/serializers.py:27:4: C0115: Missing class docstring (missing-class-docstring)
workflows/serializers.py:27:4: R0903: Too few public methods (0/2) (too-few-public-methods)
workflows/serializers.py:40:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
workflows/serializers.py:48:12: C0103: Variable name "pk" doesn't conform to snake_case naming style (invalid-name)
workflows/serializers.py:51:12: W0707: Consider explicitly re-raising using 'except (ValueError, ObjectDoesNotExist) as exc' and 'raise serializers.ValidationError([f"Couldn't find any 'previous' plugin instance with id {previous_plugin_inst_id}."]) from exc' (raise-missing-from)
workflows/serializers.py:61:4: R0914: Too many local variables (17/15) (too-many-locals)
workflows/serializers.py:80:12: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise serializers.ValidationError([f'Invalid JSON string {nodes_info}.']) from exc' (raise-missing-from)
workflows/serializers.py:84:12: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
workflows/serializers.py:96:16: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
workflows/serializers.py:108:24: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise serializers.ValidationError(msg) from exc' (raise-missing-from)
workflows/serializers.py:126:16: C0103: Variable name "d" doesn't conform to snake_case naming style (invalid-name)
workflows/serializers.py:61:4: R0912: Too many branches (20/12) (too-many-branches)
workflows/serializers.py:61:4: R0915: Too many statements (53/50) (too-many-statements)
workflows/serializers.py:154:8: C0103: Variable name "l" doesn't conform to snake_case naming style (invalid-name)
workflows/serializers.py:177:16: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise serializers.ValidationError(msg) from exc' (raise-missing-from)
************* Module workflows._types
workflows/_types.py:55:0: C0301: Line too long (113/100) (line-too-long)
workflows/_types.py:80:0: C0301: Line too long (111/100) (line-too-long)
workflows/_types.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/_types.py:18:0: C0115: Missing class docstring (missing-class-docstring)
workflows/_types.py:52:4: C0116: Missing function or method docstring (missing-function-docstring)
workflows/_types.py:55:4: C0116: Missing function or method docstring (missing-function-docstring)
workflows/_types.py:61:4: C0116: Missing function or method docstring (missing-function-docstring)
workflows/_types.py:88:8: C0103: Variable name "l" doesn't conform to snake_case naming style (invalid-name)
workflows/_types.py:94:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
************* Module workflows.views
workflows/views.py:1:0: C0114: Missing module docstring (missing-module-docstring)
workflows/views.py:3:0: E0401: Unable to import 'rest_framework' (import-error)
workflows/views.py:4:0: E0401: Unable to import 'rest_framework.reverse' (import-error)
workflows/views.py:28:4: R0914: Too many local variables (21/15) (too-many-locals)
workflows/views.py:63:16: W0622: Redefining built-in 'id' (redefined-builtin)
workflows/views.py:59:14: C1802: Do not use `len(SEQUENCE)` without comparison to determine if a sequence is empty (use-implicit-booleaness-not-len)
workflows/views.py:63:16: C0103: Variable name "id" doesn't conform to snake_case naming style (invalid-name)
workflows/views.py:74:0: W0613: Unused argument 'args' (unused-argument)
workflows/views.py:74:0: W0613: Unused argument 'kwargs' (unused-argument)
workflows/views.py:133:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
workflows/views.py:120:0: R0903: Too few public methods (1/2) (too-few-public-methods)
workflows/views.py:142:0: R0903: Too few public methods (0/2) (too-few-public-methods)
workflows/views.py:166:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
workflows/views.py:178:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
workflows/views.py:191:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
workflows/views.py:203:19: W0613: Unused argument 'request' (unused-argument)
workflows/views.py:203:0: W0613: Unused argument 'args' (unused-argument)
workflows/views.py:203:0: W0613: Unused argument 'kwargs' (unused-argument)

------------------------------------------------------------------
Your code has been rated at 6.31/10

The above needs to be fixed.

**Comment by pridhi-arora** [comment]
@jennydaman Please assign this to me.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
