### ISSUE TITLE
Fix lint errors across module: manage

### ISSUE THREAD

**Issue by pridhi-arora** [FNNDSC/ChRIS_ultron_backEnd#468]
Following is the output of `pylint manage.py`

************* Module manage
manage.py:12:8: C0415: Import outside toplevel (django.core.management.execute_from_command_line) (import-outside-toplevel)

------------------------------------------------------------------
Your code has been rated at 9.09/10

The above needs to be fixed.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/458#issuecomment-1302034685
