### ISSUE TITLE
Add new nodes to galena

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ultron_backEnd#496]

**Comment by Roseline-Bassey** [comment]
Hey @rudolphpienaar , I'm Roseline, an Outreachy applicant. I'll like to work on this issue. 

I'd like to ask if you could share more information about this issue or please point me to the right repo, file or documentation to get started. Thank you.

**Comment by jennydaman** [comment]
@Roseline-Bassey this issue is created for internal tracking purposes, and is not suitable for Outreachy applicants.

I suggest you find an issue which has an explanation or is labeled with "enhancement", "bug", and/or "good first issue." You may also propose issues yourself.
