### ISSUE TITLE
Deleting a FS-type plugin instance corrupts database

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#502]
Users are allowed to delete plugin instances regardless of their plugin's type (fs, ds, or ts). The invariant that "every feed has exactly one fs-type plugin instance" is broken when a user deletes a fs-type plugin instance.

After deleting a fs-type plugin instance, CUBE returns "500 Internal Server Error" when listing feeds on `api/v1/`. The owner of the now-invalid feed is affected, as well as any other user who the feed is shared with, and the `chris` user as well.

## Cleanup

If this happened to your ChRIS instance, run a SQL query on the database to find invalid feeds: "Print the ID and name of all feeds which do not have any fs-type plugin instances."

```sql
SELECT Feed.id, Feed.name
FROM feeds_feed AS Feed
LEFT OUTER JOIN (
    SELECT PInst.id AS plinst_id, PInst.feed_id AS feed_id, PMeta.name AS plugin_name
    from plugininstances_plugininstance AS PInst
    INNER JOIN plugins_plugin AS Plugins ON PInst.plugin_id = Plugins.id
    INNER JOIN plugins_pluginmeta AS PMeta ON Plugins.meta_id = PMeta.id
    WHERE PMeta.type = 'fs'
    ) AS PInst
ON PInst.feed_id = Feed.id
WHERE plinst_id IS NULL;
```

For every row returned by the query above, use a HTTP DELETE request to delete the feed. e.g.

```shell
curl -X DELETE -u chris:chris1234 https://example.com/api/v1/345/
```

**Comment by jennydaman** [comment]
# Proposed Fix A

Disallow the deletion of fs-type plugin instances.

# Proposed Fix B

When deleting a fs-type plugin instance, also delete its feed.

**Comment by rudolphpienaar** [comment]
@jennydaman -- how did/do you delete the FS plugin instance?

**Comment by jennydaman** [comment]
Just an example on localhost...

```shell
xh DELETE -a chris:chris1234 :8000/api/v1/plugins/instances/1/
```

**Comment by jennydaman** [comment]
closed by https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/506
